
target("extfs")
    set_kind("shared")
    set_basename("extfs")
    add_files("**.c")
    add_includedirs("$(projectdir)/module/all_include", {public = true})
    add_includedirs("$(projectdir)/module/extfs/lwext4/include", {public = true})
    add_includedirs("$(projectdir)/module/extfs", {public = true})
    set_targetdir("$(builddir)/kmod")
    add_cflags("-fPIC")
    add_cflags("-fvisibility=hidden")
    add_cflags("-fno-stack-protector")
    add_ldflags("-nostdlib")
    add_ldflags("-Wl,-e,dlmain", {force = true})
