default_entry: 1
timeout: 0
verbose: yes

wallpaper: boot():/background.jpg

/CoolPotOS-CP_Kernel-x86_64
    protocol: limine
    kernel_path: boot():/cpkrnl_x64.elf
    module_path: boot():/readme.txt
    module_path: boot():/e1000.km
    module_path: boot():/fatfs.km
    module_path: boot():/extfs.km
    module_path: boot():/iso9660.km
    module_path: boot():/initramfs.img
    kernel_cmdline: console=tty0 root=/dev/sata0p1 mem=default init=/bin/sh
    kaslr: no

/CoolPotOS-CP_Kernel-riscv64
    protocol: limine
    kernel_path: boot():/cpkrnl_rv64.elf
    cmdline: desktop=1
