timeout: 3

/Boot CoolPotOS (architecture: x86_64)
    protocol: limine
    kernel_path: boot():/cpkrnl64.elf
    module_path: boot():/readme.txt
    module_path: boot():/shell.elf
    kaslr: no

/Boot CoolPotOS (architecture: i386)
    protocol: multiboot1
    kernel_path: boot():/cpkrnl32.elf
    cmdline: desktop=1
