target("e1000")
    set_kind("shared")
    set_basename("e1000")
    add_files("**.c")
    add_includedirs("$(projectdir)/module/all_include", {public = true})
    add_includedirs("$(projectdir)/module/e1000", {public = true})
    set_targetdir("$(builddir)/kmod")
    add_cflags("-fPIC")
    add_cflags("-fvisibility=hidden")
    add_cflags("-fno-stack-protector")
    add_ldflags("-nostdlib")
    add_ldflags("-Wl,-e,dlmain", {force = true})